package com.codeassist.tool;

import com.codeassist.agent.AgentContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * HTML 输出工具。
 * Agent 生成交互式 HTML 报告并自动在浏览器中打开。
 * 对应 MiniClaude 的 HTML 输出功能。
 */
public class HtmlOutputTool implements Tool<HtmlOutputTool.Input, HtmlOutputTool.Output> {

    public static final String NAME = "HtmlOutput";
    private static final ObjectMapper MAPPER = new ObjectMapper();

    private static final Path OUTPUT_DIR = Paths.get(System.getProperty("user.dir"), ".ca-html-output");

    public record Input(
        String title,
        String bodyHtml,
        String filename
    ) {}

    public record Output(
        String filePath,
        int sizeBytes,
        boolean opened
    ) {}

    @Override
    public String name() { return NAME; }

    @Override
    public String description() {
        return "生成 HTML 报告并在浏览器中打开。适用于创建交互式可视化报告、代码审查结果、测试报告等。";
    }

    @Override
    public String inputSchema() {
        return """
        {
            "type": "object",
            "properties": {
                "title": { "type": "string", "description": "HTML 页面标题" },
                "bodyHtml": {
                    "type": "string",
                    "description": "HTML body 内容（完整的 HTML 标签，如 <h1>、<table>、<div> 等）"
                },
                "filename": {
                    "type": "string",
                    "description": "文件名（不含路径，默认 'report.html'）"
                }
            },
            "required": ["title", "bodyHtml"]
        }
        """;
    }

    @Override
    public Output execute(Input input, AgentContext context) throws ToolException {
        try {
            Files.createDirectories(OUTPUT_DIR);

            String filename = (input.filename() != null && !input.filename().isBlank())
                ? input.filename() : "report.html";
            if (!filename.endsWith(".html")) filename += ".html";

            Path outputFile = OUTPUT_DIR.resolve(filename);

            String html = buildHtml(input.title(), input.bodyHtml());

            byte[] bytes = html.getBytes(StandardCharsets.UTF_8);
            Files.write(outputFile, bytes);

            // 尝试在浏览器中打开
            boolean opened = openInBrowser(outputFile);

            return new Output(outputFile.toAbsolutePath().toString(), bytes.length, opened);
        } catch (Exception e) {
            throw new ToolException("生成 HTML 失败: " + e.getMessage());
        }
    }

    private String buildHtml(String title, String bodyHtml) {
        return """
        <!DOCTYPE html>
        <html lang="zh-CN">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>%s</title>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                       max-width: 960px; margin: 0 auto; padding: 20px; line-height: 1.6; color: #333; }
                h1 { color: #1a1a2e; border-bottom: 2px solid #e94560; padding-bottom: 8px; }
                h2 { color: #16213e; margin-top: 24px; }
                table { border-collapse: collapse; width: 100%%; margin: 12px 0; }
                th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
                th { background: #1a1a2e; color: white; }
                tr:nth-child(even) { background: #f8f9fa; }
                .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }
                .badge-ok { background: #d4edda; color: #155724; }
                .badge-fail { background: #f8d7da; color: #721c24; }
                code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 14px; }
                pre { background: #f4f4f4; padding: 12px; border-radius: 6px; overflow-x: auto; }
                footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #ddd; font-size: 12px; color: #888; }
            </style>
        </head>
        <body>
            %s
            <footer>Generated by Java Code Assistant</footer>
        </body>
        </html>
        """.formatted(escapeHtml(title), bodyHtml);
    }

    private String escapeHtml(String text) {
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }

    private boolean openInBrowser(Path file) {
        try {
            String os = System.getProperty("os.name").toLowerCase();
            if (os.contains("win")) {
                Runtime.getRuntime().exec(new String[]{"rundll32", "url.dll,FileProtocolHandler", file.toUri().toString()});
            } else if (os.contains("mac")) {
                Runtime.getRuntime().exec(new String[]{"open", file.toString()});
            } else {
                Runtime.getRuntime().exec(new String[]{"xdg-open", file.toString()});
            }
            return true;
        } catch (IOException e) {
            return false;
        }
    }

    @Override
    public boolean isReadOnly() { return false; }

    @Override
    public Input parseInput(String jsonInput) throws ToolException {
        try {
            JsonNode n = MAPPER.readTree(jsonInput);
            return new Input(
                n.has("title") ? n.get("title").asText() : "Report",
                n.has("bodyHtml") ? n.get("bodyHtml").asText() : "",
                n.has("filename") && !n.get("filename").isNull() ? n.get("filename").asText() : null);
        } catch (Exception e) {
            throw new ToolException("解析输入失败: " + e.getMessage());
        }
    }

    @Override
    public String formatOutput(Output output) {
        try {
            return MAPPER.writeValueAsString(output);
        } catch (Exception e) {
            return String.format("HTML 已生成: %s (%d 字节)%s",
                output.filePath(), output.sizeBytes(),
                output.opened() ? " [已在浏览器打开]" : "");
        }
    }
}
